# Generated by Django 4.2.4 on 2023-08-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_checker', '0005_alter_athlete_avg_hsr_alter_athlete_avg_jogging_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='1990-01-01')),
                ('end_date', models.DateField(default='1990-02-01')),
                ('parameter', models.CharField(choices=[('total_distance', 'Total Distance'), ('acceleration', 'Acceleration')], max_length=50)),
                ('athletes', models.ManyToManyField(blank=True, to='data_checker.athlete')),
            ],
        ),
    ]
