# Generated by Django 4.2.4 on 2023-08-17 19:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_setting_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='competition_ratio',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
