# Generated by Django 4.2.4 on 2023-08-17 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_setting_competition_ratio_setting_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
