# Generated by Django 4.2.4 on 2023-08-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_setting_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='setting',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.setting'),
            preserve_default=False,
        ),
    ]
