# Generated by Django 4.2.4 on 2023-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_setting_user_id_profile_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='parameter',
            field=models.CharField(choices=[('max', 'Maximal Distance'), ('avg', 'Average Distance')], max_length=50),
        ),
    ]
