# Generated by Django 4.2.4 on 2023-08-14 19:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_data',
            fields=[
                ('td', models.IntegerField(blank=True, null=True)),
                ('sprinting', models.IntegerField(blank=True, null=True)),
                ('HSR', models.IntegerField(blank=True, null=True)),
                ('running', models.IntegerField(blank=True, null=True)),
                ('jogging', models.IntegerField(blank=True, null=True)),
                ('walking', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='HSR',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='jogging',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='running',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='sprinting',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='td',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='walking',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.AddField(
            model_name='activity_data',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_checker.activity'),
        ),
        migrations.AddField(
            model_name='activity_data',
            name='athlete',
            field=models.ManyToManyField(to='data_checker.athlete'),
        ),
    ]
