# Generated by Django 4.2.4 on 2023-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_checker', '0003_activity_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='name',
        ),
        migrations.AddField(
            model_name='athlete',
            name='avg_HSR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='avg_jogging',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='avg_running',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='avg_sprinting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='avg_td',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='avg_walking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Activity_data',
        ),
    ]
