# Generated by Django 4.2.4 on 2023-08-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_checker', '0004_remove_athlete_name_athlete_avg_hsr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='avg_HSR',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='avg_jogging',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='avg_running',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='avg_sprinting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='avg_td',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='avg_walking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='max_HSR',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='max_jogging',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='max_running',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='max_sprinting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='max_td',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='max_walking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
