# Generated by Django 4.2.4 on 2023-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_checker', '0007_alter_athlete_options_tempdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='temp_HSR',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='temp_jogging',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='temp_jogging2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='temp_running',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='temp_sprinting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='temp_td',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='temp_walking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='TempData',
        ),
    ]
